FROM node:20-alpine
WORKDIR /workspace/apps/web

COPY package.json pnpm-lock.yaml* .npmrc* ./
RUN corepack enable && corepack prepare pnpm@9.6.0 --activate && pnpm i

COPY . .
EXPOSE 3000
CMD ["pnpm", "dev"]
