name: audit
on:
  pull_request:
  schedule:
    - cron: "0 18 * * 0"

jobs:
  pnpm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Audit (fail on high and above)
        run: pnpm dlx audit-ci --config ./.audit-ci.json --report-type summary
