name: Web Tests

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-test.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm --filter @sou-hyou/web lint

      - name: Type check
        run: pnpm --filter @sou-hyou/web run build --dry-run || pnpm --filter @sou-hyou/web run tsc --noEmit

      - name: Run tests
        run: pnpm --filter @sou-hyou/web test

      - name: Build app
        run: pnpm --filter @sou-hyou/web build
        env:
          NEXT_PUBLIC_GRAPHQL_URL: http://localhost:4000/graphql
          NEXT_PUBLIC_FB_API_KEY: ${{ secrets.NEXT_PUBLIC_FB_API_KEY }}
          NEXT_PUBLIC_FB_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FB_AUTH_DOMAIN }}
          NEXT_PUBLIC_FB_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FB_PROJECT_ID }}
